stages:
  - build
  - test
  - deploy

unit_test:
  stage: test

  tags:
    - python

  script:
    - cat << EOF > credentials
      [DEFAULT]
      VERACODE_API_ID = ${VERACODE_API_ID}
      VERACODE_API_SECRET = ${VERACODE_API_SECRET}
      EOF
    - pip3 install -r requirements.txt
    - python3 tests.py

