stages:
  - build
  - test
  - deploy

unit_test:
  stage: test

  tags:
    - python

  script:
    - echo "[DEFAULT]" > credentials
    - echo "VERACODE_API_ID = ${VERACODE_API_ID}" >> credentials
    - echo "VERACODE_API_SECRET = ${VERACODE_API_SECRET}" >> credentials
    - cat credentials
    - pip3 install -r requirements.txt
    - python3 tests.py

