stages:
  - build
  - test
  - deploy

unit_test:
  stage: test

  tags:
    - python

  script:
    - echo "[DEFAULT] \n
      VERACODE_API_ID = ${VERACODE_API_ID} \n
      VERACODE_API_SECRET = ${VERACODE_API_SECRET} \n
      " > credentials
    - pip3 install -r requirements.txt
    - python3 tests.py

