stages:
  - test
  - deploy

unit_test:
  stage: test

  tags:
    - python

  script:
    - mkdir ~/.veracode
    - echo "[DEFAULT]" > ~/.veracode/credentials
    - echo "VERACODE_API_ID = ${VERACODE_API_ID}" >> ~/.veracode/credentials
    - echo "VERACODE_API_SECRET = ${VERACODE_API_SECRET}" >> ~/.veracode/credentials
    - pip3 install -r requirements.txt
    - python3 tests.py

deploy:
    stage: deploy
    script:
        - export VERSION=$(python3 increment_version.py)
        - echo $VERSION

    only:
        - master
        - dev
